### ISSUE TITLE
Link to docs without building?

### ISSUE THREAD

**Issue by estiens** [adafruit/Adafruit_CircuitPython_TrellisM4#16]
Many of us might find our way here looking to use the circuitpython library for the neotrellis. Could we have a link to the docs rather than having to clone the repo and build the docs ourselves? Or am I missing it? Thanks for the library and examples!

**Comment by siddacious** [comment]
@estiens I believe this is what you're looking for https://circuitpython.readthedocs.io/projects/trellism4/en/latest/

We'll certainly make an effort to make this page easier to locate.

**Comment by estiens** [comment]
Thanks so much! +1+
